# Generated by Django 5.1.3 on 2025-01-03 11:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FocusFlow', '0002_remove_projet_user_tache_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='user',
            field=models.ManyToManyField(related_name='participes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tache',
            name='user',
            field=models.ManyToManyField(related_name='taches', to=settings.AUTH_USER_MODEL),
        ),
    ]
